### ISSUE TITLE
YouTube command returns an error message

### ISSUE THREAD

**Issue by EditeurCode** [AoDude/RuneInfo#15]
Error: Bad Request
    at Request.callback (C:\workspace\runeinfo\node_modules\superagent\lib\node\index.js:674:11)
    at C:\workspace\runeinfo\node_modules\superagent\lib\node\index.js:881:18
    at IncomingMessage.<anonymous> (C:\workspace\runeinfo\node_modules\superagent\lib\node\parsers\json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process,ext_tick.js:80:11)
    at process._tickCallback (internal/process,ext_tick.js:104:9)

**Comment by AoDude** [comment]
I am looking into this, it appears YouTube has changed how their RSS works (completely removing what I was leveraging).

**Comment by AoDude** [comment]
It appears YouTube has fixed their RSS, as the command has now begun working again with no changes.
