### ISSUE TITLE
discord?

### ISSUE THREAD

**Issue by hyraelle** [AoDude/RuneInfo#68]
You should not be seeing this!,Please file an issue here: https://github.com/AoDude/RuneInfo,Alternatively report this in the official RuneInfo Guild here: https://discord.gg/TrDnKtQ
Error:
AbortError: The user aborted a request.
    at abort (/home/bdistin/Documents/RuneInfo,ode_modules,ode-fetch/lib/index.js:1412:16)
    at AbortSignal.abortAndFinalize (/home/bdistin/Documents/RuneInfo,ode_modules,ode-fetch/lib/index.js:1427:4)
    at AbortSignal.dispatchEvent (/home/bdistin/Documents/RuneInfo,ode_modules/event-target-shim/src/event-target.mjs:337:35)
    at abortSignal (/home/bdistin/Documents/RuneInfo,ode_modules/abort-controller/src/abort-signal.ts:68:12)
    at AbortController.abort (/home/bdistin/Documents/RuneInfo,ode_modules/abort-controller/src/abort-controller.ts:26:9)
    at /home/bdistin/Documents/RuneInfo,ode_modules/@klasa/rest/src/lib/RequestHandler.ts:117:60
    at Timeout.<anonymous> (/home/bdistin/Documents/RuneInfo,ode_modules/@klasa/timer-manager/src/index.ts:25:4)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)

RuneInfo•Aujourd’hui à 16:44

![image](https://user-images.githubusercontent.com/56530028/99592100-b9eff280-29bd-11eb-9594-ec1adf33fdd7.png)

**Comment by AoDude** [comment]
Discord API issue: https://discord.statuspage.io/incidents/1j6ttn9rq365
